Repository p5quared/apple-music.nvim, pull requests merged in 2024-07, with the labels that each got.

#8 Fix: Broken list items by comma
  lua/apple-music/init.lua
Labels: bug

#12 Move temporary playlist note up
  README.md
Labels: documentation

#13 Feat: Change current track's favorited state
  lua/apple-music/init.lua
Labels: enhancement

#22 Fix: Quoted names breaking scripts
  lua/apple-music/init.lua
Labels: bug

#23 Feat #14: Toggle favorited/loved
  lua/apple-music/init.lua
Labels: enhancement
